spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/jira
    driver-class-name: org.postgresql.Driver
    username: jira
    password: jira
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
